In [2]:
import numpy as np
rng = np.random.default_rng(seed=42)
print("NumPy version:", np.__version__)

NumPy version: 2.3.5


In [4]:
#array creation example
#create an array from python list 
list_data = [1, 2, 3, 4, 5]
arr_from_list = np.array(list_data)
print("array from list:", arr_from_list)

array from list: [1 2 3 4 5]


In [7]:
type(arr_from_list)


numpy.ndarray

In [9]:
#creating an array of zeros 
arr_zeros = np.zeros((2, 3)) #2*3 matrix of zeros
print("\narray of zero's :\n", arr_zeros)


array of zero's :
 [[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
#creating an array of ones 
arr_ones = np.ones((2, 3)) #2*3 matrix of ones 
print("\narray of ones :\n", arr_ones)


array of ones :
 [[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
arr_ones.shape

(2, 3)

In [14]:
arr_ones.ndim

2